# your domain
domain: lcrproxypool.tk

# database url
database_url: ""

# cloudflare api
cf_email: "3309632925@qq.com"
cf_key: "a39fd7355531b774f9b3ac973b7ef7b0f393a"

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://example.com/source.yaml
